VaaaN/MultiLaneFreeFlow/WebApplication/MLFFWebApplication/Controllers/POSController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using VaaaN.MLFF.Libraries.CommonLibrary.CBE;
using VaaaN.MLFF.WebApplication.Models;

namespace VaaaN.MLFF.WebApplication.Controllers
{
    public class POSController : Controller
    {
        int tmsId = 1;
        // GET: POS
        public ActionResult Index()
        {
            return View();
        }


        //Get
        public ActionResult CustomerRegistrationList()
        {
            try
            {
                if (Session["LoggedUserId"] == null)
                {
                    return RedirectToAction("SessionPage", "Home");
                }
                ViewBag.MainMenu = HelperClass.NewMenu(Convert.ToInt16(Session["LoggedUserId"]));
            }
            catch (Exception ex)
            {

                HelperClass.LogMessage("Failed to load Customer Registration List in POS Controller" + ex);
            }
            return View();
        }

        #region Register Customer
        public ActionResult RegisterCustomerList()
        {

            List<VaaaN.MLFF.Libraries.CommonLibrary.CBE.CustomerAccountCBE> customerDataList = new List<Libraries.CommonLibrary.CBE.CustomerAccountCBE>();

            try
            {
                if (Session["LoggedUserId"] == null)
                {
                    return RedirectToAction("SessionPage", "Home");
                }
                ViewBag.MainMenu = HelperClass.NewMenu(Convert.ToInt16(Session["LoggedUserId"]));
                //Call Bll To get all Plaza List
                customerDataList = VaaaN.MLFF.Libraries.CommonLibrary.BLL.CustomerAccountBLL.GetAllAsList();

                return View(customerDataList);

            }
            catch (Exception ex)
            {

                HelperClass.LogMessage("Failed To Load TagSaleList in POS Controller" + ex);
            }
            return View(customerDataList);
        }
        //Get
        [HttpGet]
        public ActionResult RegisterCustomer()
        {
            try
            {
                if (Session["LoggedUserId"] == null)
                {
                    return RedirectToAction("SessionPage", "Home");
                }
                ViewBag.MainMenu = HelperClass.NewMenu(Convert.ToInt16(Session["LoggedUserId"]));
                #region Bind Province DropDowm
                List<SelectListItem> provincelist = new List<SelectListItem>();
                List<VaaaN.MLFF.Libraries.CommonLibrary.CBE.ProvinceCBE> province = VaaaN.MLFF.Libraries.CommonLibrary.BLL.ProvinceBLL.GetAll().Cast<VaaaN.MLFF.Libraries.CommonLibrary.CBE.ProvinceCBE>().ToList();

                provincelist.Add(new SelectListItem() { Text = "--Select Province--", Value = "0" });
                foreach (VaaaN.MLFF.Libraries.CommonLibrary.CBE.ProvinceCBE cr in province)
                {
                    provincelist.Add(new SelectListItem() { Text = cr.ProvinceName, Value = System.Convert.ToString(cr.ProvinceId) });
                }

                ViewBag.Provinces = provincelist;

                #endregion

                #region Gender
                List<SelectListItem> genderList = new List<SelectListItem>();
                Array argender = Enum.GetValues(typeof(VaaaN.MLFF.Libraries.CommonLibrary.Constants.Gender));

                for (int i = 0; i < argender.Length; i++)
                {
                    genderList.Add(new SelectListItem() { Text = VaaaN.MLFF.Libraries.CommonLibrary.Constants.GenderName[i], Value = System.Convert.ToString((int)argender.GetValue(i)) });
                }
                ViewBag.genderName = genderList;

                #endregion
                #region MaritalStatus
                List<SelectListItem> maritalstatusList = new List<SelectListItem>();
                Array armaritalstatus = Enum.GetValues(typeof(VaaaN.MLFF.Libraries.CommonLibrary.Constants.MaritalStatus));

                for (int i = 0; i < armaritalstatus.Length; i++)
                {
                    maritalstatusList.Add(new SelectListItem() { Text = VaaaN.MLFF.Libraries.CommonLibrary.Constants.MaritalStatusName[i], Value = System.Convert.ToString((int)armaritalstatus.GetValue(i)) });
                }
                ViewBag.maritalstatusName = maritalstatusList;

                #endregion
                #region Nationality
                List<SelectListItem> nationalityList = new List<SelectListItem>();
                Array arnationality = Enum.GetValues(typeof(VaaaN.MLFF.Libraries.CommonLibrary.Constants.Nationality));

                for (int i = 0; i < arnationality.Length; i++)
                {
                    nationalityList.Add(new SelectListItem() { Text = VaaaN.MLFF.Libraries.CommonLibrary.Constants.NationalityName[i], Value = System.Convert.ToString((int)arnationality.GetValue(i)) });
                }
                ViewBag.nationalityName = nationalityList;

                #endregion

            }
            catch (Exception ex)
            {

                HelperClass.LogMessage("Failed to load Register Customer in POS Controller" + ex);
            }
            return View();
        }

        [HttpPost]
        public ActionResult RegisterCustomer(Libraries.CommonLibrary.CBE.CustomerAccountCBE customerAccount, FormCollection form)
        {

            try
            {
                if (Session["LoggedUserId"] == null)
                {
                    return RedirectToAction("SessionPage", "Home");
                }
                ViewBag.MainMenu = HelperClass.NewMenu(Convert.ToInt16(Session["LoggedUserId"]));
                #region Bind Province DropDowm
                List<SelectListItem> provincelist = new List<SelectListItem>();
                List<VaaaN.MLFF.Libraries.CommonLibrary.CBE.ProvinceCBE> province = VaaaN.MLFF.Libraries.CommonLibrary.BLL.ProvinceBLL.GetAll().Cast<VaaaN.MLFF.Libraries.CommonLibrary.CBE.ProvinceCBE>().ToList();

                provincelist.Add(new SelectListItem() { Text = "--Select Province--", Value = "0" });
                foreach (VaaaN.MLFF.Libraries.CommonLibrary.CBE.ProvinceCBE cr in province)
                {
                    provincelist.Add(new SelectListItem() { Text = cr.ProvinceName, Value = System.Convert.ToString(cr.ProvinceId) });
                }

                ViewBag.Provinces = provincelist;

                #endregion

                #region Gender
                List<SelectListItem> genderList = new List<SelectListItem>();
                Array argender = Enum.GetValues(typeof(VaaaN.MLFF.Libraries.CommonLibrary.Constants.Gender));

                for (int i = 0; i < argender.Length; i++)
                {
                    genderList.Add(new SelectListItem() { Text = VaaaN.MLFF.Libraries.CommonLibrary.Constants.GenderName[i], Value = System.Convert.ToString((int)argender.GetValue(i)) });
                }
                ViewBag.genderName = genderList;

                #endregion

                #region MaritalStatus
                List<SelectListItem> maritalstatusList = new List<SelectListItem>();
                Array armaritalstatus = Enum.GetValues(typeof(VaaaN.MLFF.Libraries.CommonLibrary.Constants.MaritalStatus));

                for (int i = 0; i < armaritalstatus.Length; i++)
                {
                    maritalstatusList.Add(new SelectListItem() { Text = VaaaN.MLFF.Libraries.CommonLibrary.Constants.MaritalStatusName[i], Value = System.Convert.ToString((int)armaritalstatus.GetValue(i)) });
                }
                ViewBag.maritalstatusName = maritalstatusList;

                #endregion

                #region Nationality
                List<SelectListItem> nationalityList = new List<SelectListItem>();
                Array arnationality = Enum.GetValues(typeof(VaaaN.MLFF.Libraries.CommonLibrary.Constants.Nationality));

                for (int i = 0; i < arnationality.Length; i++)
                {
                    nationalityList.Add(new SelectListItem() { Text = VaaaN.MLFF.Libraries.CommonLibrary.Constants.NationalityName[i], Value = System.Convert.ToString((int)arnationality.GetValue(i)) });
                }
                ViewBag.nationalityName = nationalityList;

                #endregion

                #region Image validate
                var imageTypes = new string[]{
                    "image/gif",
                    "image/jpg",
                    "image/jpeg",
                    "image/png"
                };
                if (customerAccount.CustomerImage != null && customerAccount.CustomerImage.ContentLength > 0)
                {
                    if (!imageTypes.Contains(customerAccount.CustomerImage.ContentType))
                    {
                        TempData["lblerror"] = "Please choose either GIF, JPG or PNG  image.";
                        return View("RegisterCustomer");
                    }

                    if (customerAccount.CustomerImage.ContentLength > 2097152) // about 2 MB
                    {
                        // Notify the user why their file was not uploaded.
                        TempData["lblerror"] = "Attachment file can not uploaded because it exceeds the 2 MB size limit.";
                        return View("RegisterCustomer");
                    }

                    #region ImageProcess
                    string customerImageName = customerAccount.ResidentId.ToString() + "_Profile_" + String.Format("{0:yyyyMMdd}", DateTime.Now);
                    string extension = System.IO.Path.GetExtension(customerAccount.CustomerImage.FileName).ToLower();



VaaaN/MultiLaneFreeFlow/WebApplication/MLFFWebApplication/Views/POS/AddCustomerTag.cshtml
@model VaaaN.MLFF.Libraries.CommonLibrary.CBE.CustomerVehicleCBE
@{
    ViewBag.Title = "Add Customer Tag";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
<style type="text/css">
    input[type='number'] {
        -moz-appearance: textfield;
    }
    /* Webkit browsers like Safari and Chrome */
    input[type=number]::-webkit-inner-spin-button,
    input[type=number]::-webkit-outer-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }
</style>
@using (Html.BeginForm("AddCustomerTag", "POS", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="panel panel-info">
        <div class="panel-heading" style="background-color:rgb(64, 178, 205);">
            <h1 class="panel-title new-title">New Tag Registration</h1>
        </div>
        <div class="panel-body">
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.VehicleClassId, htmlAttributes: new { @class = "control-label col-md-2 required" })
                    <div class="col-md-4">
                        @Html.DropDownList("ddlVehicleClass", (IEnumerable<SelectListItem>)ViewBag.VehicleClass, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.VehicleClassId, "", new { @class = "text-danger" })
                    </div>
                    @Html.LabelFor(model => model.VehRegNo, htmlAttributes: new { @class = "control-label col-md-2 required" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.VehRegNo, new { htmlAttributes = new { @class = "form-control " } })
                        @Html.ValidationMessageFor(model => model.VehRegNo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TagId, htmlAttributes: new { @class = "control-label col-md-2 required" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.TagId, new { htmlAttributes = new { @class = "form-control ", autofocus = "true" } })
                        @Html.ValidationMessageFor(model => model.TagId, "", new { @class = "text-danger" })
                    </div>
                    @Html.LabelFor(model => model.Amount, htmlAttributes: new { @class = "control-label col-md-2 required" })
                    <div class="col-md-4">
                        @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control ", autofocus = "true" } })
                        @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group"><span id="lblErrors" style="color:red;float:right">@TempData["lblerror"]</span>
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Submit" class="btn btn-primary" />
                        &nbsp;&nbsp;@Html.ActionLink("Back", "TagSaleList", "POS",new {id = ViewBag.AccountId }, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
    </div>
}

VaaaN/MultiLaneFreeFlow/WebApplication/MLFFWebApplication/Views/POS/CustomerTagList.cshtml
@model IEnumerable<VaaaN.MLFF.Libraries.CommonLibrary.CBE.CustomerVehicleCBE>

@{
    ViewBag.Title = "Customer Vehicle List";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<script src="~/scripts/jquery.dataTables.min.js"></script>
<script src="~/scripts/dataTables.bootstrap.min.js"></script>
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.4/css/jquery.dataTables.min.css">

<script type="text/javascript">
    $(document).ready(function () {
        $('#tableCustomerVehicle').dataTable({
            "paging": true,
            "ordering": false,
            "info": true,
            "searching": true
        });
    });
</script>


<div class="panel panel-info">
    <div class="panel-heading " style="background-color:rgb(64, 178, 205);">
        @{ int rowNo = 0; }
        <div class="panel-title new-title">
            Customer Vehicle List
        </div>

    </div>
    <div style="height:5px;"></div>
    <table id="tableCustomerVehicle" class="table table-condensed table-striped table-hover">
        <thead>
            <tr>
                <th>
                    No.
                </th>
                <th>
                   @VaaaN.MLFF.Libraries.CommonLibrary.Resource.Resourceen.VehicleRegNo
                </th>

                <th>
                  @VaaaN.MLFF.Libraries.CommonLibrary.Resource.Resourceen.TagId
                </th>
                <th>
                   @VaaaN.MLFF.Libraries.CommonLibrary.Resource.Resourceen.VehicleClass
                </th>

                <th>
                    Edit
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @(rowNo += 1)

                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VehRegNo)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.TagId)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.VehicleClassName)
                    </td>


                    <td>
                        <a class="edit" href="#"><i class="fa fa-pencil-square-o" title="Edit"></i></a>


                    </td>
                </tr>

            }
        </tbody>
    </table>
    <p style="padding-top:15px;">
        <a href="@Url.Action("AddCustomerTag", "POS", new { id =ViewBag.AccountId })" class="btn btn-primary"><i class="fa fa-plus-circle"></i><span> New Tag</span></a>
        &nbsp;&nbsp;<a href="@Url.Action("AddCustomerRecharge", "POS", new { id =ViewBag.AccountId })" class="btn btn-primary"><i class="fa fa-plus-circle"></i><span> New Recharge</span></a>

    </p>
</div>

VaaaN/MultiLaneFreeFlow/WebApplication/MLFFWebApplication/Views/POS/RegisterCustomer.cshtml
@model VaaaN.MLFF.Libraries.CommonLibrary.CBE.CustomerAccountCBE
@{
    ViewBag.Title = "Register Customer";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
<style type="text/css">
    input[type='number'] {
        -moz-appearance: textfield;
    }
    /* Webkit browsers like Safari and Chrome */
    input[type=number]::-webkit-inner-spin-button,
    input[type=number]::-webkit-outer-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }

    #dvPreview {
        filter: progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod=image);
        display: none;
        float: left;
        position: absolute;
        left: 0px;
        top: 0px;
        z-index: 1000;
        background-color: #204d74;
        padding: 2px;
        color: #FFFFFF;
        font-weight: bold;
    }

    #dvPreview img {
            height: 120px;
            width: 300px;
        }
</style>
<script src="~/js/CustomerAccount.js"></script>
@using (Html.BeginForm("RegisterCustomer", "POS", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="panel panel-info">
        <div class="panel-heading" style="background-color:rgb(64, 178, 205);">
            <h1 class="panel-title new-title">New Registration</h1>
        </div>
        <div class="panel-body">
            @{
                <input type="hidden" id="hfCustomerImagePath" value="" />
                <input type="hidden" id="hfCustomerDocumentPath" value="" />
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.ResidentId, htmlAttributes: new { @class = "control-label col-md-2 required" })
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.ResidentId, new { htmlAttributes = new { @class = "form-control ", autofocus = "true" } })
                            @Html.ValidationMessageFor(model => model.ResidentId, "", new { @class = "text-danger" })
                        </div>
                        @Html.Label("Name", htmlAttributes: new { @class = "control-label col-md-2 required" })
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control ", autofocus = "true" } })
                            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "control-label col-md-2 required" })
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control " } })
                            @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
                        </div>
                        @Html.LabelFor(model => model.EmailId, htmlAttributes: new { @class = "control-label col-md-2 required" })
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.EmailId, new { htmlAttributes = new { @class = "form-control " } })
                            @Html.ValidationMessageFor(model => model.EmailId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.BirthPlace, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.BirthPlace, new { htmlAttributes = new { @class = "form-control " } })
                        </div>
                        @Html.Label("Birth Date", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control " } })
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.RT, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.RT, new { htmlAttributes = new { @class = "form-control " } })
                            @Html.ValidationMessageFor(model => model.RT, "", new { @class = "text-danger" })
                        </div>
                        @Html.LabelFor(model => model.RW, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.RW, new { htmlAttributes = new { @class = "form-control " } })
                            @Html.ValidationMessageFor(model => model.RW, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2 required" })
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control " } })
                            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                        </div>
                        @Html.LabelFor(model => model.ProvinceId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            @Html.DropDownList("ProvinceId", (IEnumerable<SelectListItem>)ViewBag.Provinces, new { @class = "form-control", onchange = "GetCityList();" })
                            @Html.ValidationMessageFor(model => model.ProvinceId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.CityId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            <select id="ddlCityId" name="ddlCityId" class="form-control" onchange="GetDistrictList();"></select>
                            @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
                        </div>
                        @Html.LabelFor(model => model.DistrictId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            <select id="DistrictId" name="DistrictId" class="form-control" onchange="GetSubDistrictList();"></select>
                            @Html.ValidationMessageFor(model => model.DistrictId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.SubDistrictId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">

                            <select id="SubDistrictId" name="SubDistrictId" class="form-control" onchange="GetZip(this);"></select>
                            @Html.ValidationMessageFor(model => model.SubDistrictId, "", new { @class = "text-danger" })
                        </div>
                        @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control " } })
                            @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Nationality, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            @Html.DropDownList("Nationality", (IEnumerable<SelectListItem>)ViewBag.nationalityName, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Nationality, "", new { @class = "text-danger" })
                        </div>
                        @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            @Html.DropDownList("Gender", (IEnumerable<SelectListItem>)ViewBag.genderName, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.MaritalStatus, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            @Html.DropDownList("MaritalStatus", (IEnumerable<SelectListItem>)ViewBag.maritalstatusName, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.MaritalStatus, "", new { @class = "text-danger" })
                        </div>
                        @Html.LabelFor(model => model.Occupation, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.Occupation, new { htmlAttributes = new { @class = "form-control " } })
                            @Html.ValidationMessageFor(model => model.Occupation, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="form-group">
                        @Html.Label("Valid Until", htmlAttributes: new { @class = "control-label col-md-2 required" })
                        <div class="col-md-4">
                            @Html.EditorFor(model => model.ValidUntil, new { htmlAttributes = new { @class = "form-control " } })
                            @Html.ValidationMessageFor(model => model.ValidUntil, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="clearfix"></div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CustomerImage, htmlAttributes: new { @class = "control-label col-md-2 required" })
                        <div class="col-md-4">
                            <input name="CustomerImage" id="imagepath" type="file" onchange="Preview(this);" />
                            @Html.ValidationMessageFor(model => model.CustomerImage, "", new { @class = "text-danger" })
                        </div>
                        @Html.LabelFor(model => model.ResidentidImage, htmlAttributes: new { @class = "control-label col-md-2 required" })
                        <div class="col-md-4">
                            <input name="ResidentidImage" id="ResidentidImage" type="file" />
                            @Html.ValidationMessageFor(model => model.ResidentidImage, "", new { @class = "text-danger" })
                        </div>

                    </div>
                    <div class="clearfix"></div>
                    <div class="form-group">
                        <div class="col-md-4" style="position: relative;">
                            <div id="dvPreview">
                            </div>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                    <div class="form-group">
                        <span id="lblErrors" style="color:red;float:right">@TempData["lblerror"]</span>
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Submit" class="btn btn-primary" onclick="return validateCustomerAccount();" />
                            &nbsp;&nbsp;@Html.ActionLink("Customer List", "registercustomerlist", "POS", new { @class = "btn btn-primary" })
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
                }

VaaaN/MultiLaneFreeFlow/WebApplication/MLFFWebApplication/Views/POS/RenderCustomerVehicle.cshtml
@model VaaaN.MLFF.Libraries.CommonLibrary.CBE.CustomerVehicleCBE

<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.VehicleClassId, htmlAttributes: new { @class = "control-label col-md-2 required" })
        <div class="col-md-4">
            @Html.DropDownList("ddlVehicleClass", (IEnumerable<SelectListItem>)ViewBag.VehicleClass, new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.VehicleClassId, "", new { @class = "text-danger" })
        </div>
        @Html.LabelFor(model => model.VehRegNo, htmlAttributes: new { @class = "control-label col-md-2 required" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.VehRegNo, new { htmlAttributes = new { @class = "form-control " } })
            @Html.ValidationMessageFor(model => model.VehRegNo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TagId, htmlAttributes: new { @class = "control-label col-md-2 required" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.TagId, new { htmlAttributes = new { @class = "form-control ", autofocus = "true" } })
            @Html.ValidationMessageFor(model => model.TagId, "", new { @class = "text-danger" })
        </div>
        <div class="pull-right">
            <input type="submit" value="Submit" class="btn btn-primary" onclick="return Validation();" />
            &nbsp;&nbsp;@Html.ActionLink("Back", "RegisterCustomerList", "Home", new { @class = "btn btn-primary" })
        </div>

    </div>
    @*<div class="form-group">
            <div class="col-md-offset-2 col-md-10">
              
            </div>
        </div>*@
</div>